function createfigure(X1, Y1, E1)
%CREATEFIGURE(X1, Y1, E1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  E1:  errorbar e

%  Auto-generated by MATLAB on 01-Oct-2018 15:28:49

% Create figure
figure1 = figure('Name',...
    'iData iD441389=rdivide(iD4... [100    1] Intensity [n/s/cm2/bin](x) "mccode.sim McCode sim file I=2.31213e+10 I_err=7.87023e+07 N=2.20095e+06 X0=1.4936 dX=0.933308;" <C:\Users\20D3~1\AppData\Local\Temp\tp97e4b0ba_058b_4900_8ba9_529c2b0d3c3d\H2-1_DC1.L>');

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 20]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 22951004923]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('I, n/s/cm^{2}/ ?');

% Create xlabel
xlabel('lambda,  ?');

legend('jojo');

% Create title
title('H2-1_DC1 , total flux =  2.31e+10  ','Interpreter','none');

% Create hggroup
hggroup1 = hggroup('Parent',axes1,'DisplayName','Monlam',...
    'Tag','plot_iD441389');

% Create plot
plot(X1,Y1,'Parent',hggroup1,'DisplayName','Monlam','Tag','plot_iD441389',...
    'LineWidth',2);

% Create errorbar
errorbar(X1,Y1,E1,'DisplayName','Monlam','Tag','plot_iD441389',...
    'Parent',hggroup1,...
    'LineStyle','none',...
    'LineWidth',2);

