focal_dist_in_h = 1, focal_dist_out_h = 1,focal_dist_in_w = 1,  focal_dist_out_w = 1,guide_length = 10, nose_length = 3, m_side = 2, m_top = 6, focal_dist = 0.5, sample_height = 0.01
[p,m]=mcstas('generic_straight.instr',struct('guide_length', 12, 'm_side', m_min:m_step:m_max, 'm_top', 6,...
    'sample_height', 0.01, 'sample_width', 0.01,...
    'guide_start_width',0.03, 'guide_start_height',0.1, 'source_lambda_min',4.85, 'source_lambda_max',4.95,...
    'cold_regime',1),struct('ncount',1e5));

